{{- if .Values.podDisruptionBudget.enabled }}
{{- $fullName := include "delos.fullname" . -}}

{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "delos.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "delos.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
