{{- $fullName := include "delos.fullname" . -}}

{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "delos.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if $.Values.metrics.enabled }}
    - port: {{ $.Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "delos.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
